name: PHP CI Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs to run
jobs:
  test:
    name: Run PHP Checks
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Use the PHP version your project requires

      # Lint PHP files (check for syntax errors)
      - name: Lint PHP files
        run: find . -type f -name '*.php' -exec php -l {} \;
      # Download PHP-CS-Fixer
      - name: Download PHP-CS-Fixer
        run: |
          wget https://cs.symfony.com/download/php-cs-fixer-v3.phar -O php-cs-fixer.phar
          chmod +x php-cs-fixer.phar

      # Run PHP-CS-Fixer (fix coding standards)
      - name: Run PHP-CS-Fixer
        run: ./php-cs-fixer.phar fix --verbose .

      # Download PHP_CodeSniffer
      - name: Download PHP_CodeSniffer
        run: |
          wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -O phpcs.phar
          chmod +x phpcs.phar

      # Run PHP_CodeSniffer (check coding standards)
      - name: Run PHP_CodeSniffer
        run: ./phpcs.phar --standard=PSR12 .